export const properties = {
  all: {
    filterTitle: 'All Catholic and Orthodox Saints',
  },
  orthodox: {
    filterTitle: 'All Orthodox Saints',
  },
  catholic: {
    filterTitle: 'All Catholic Saints',
  },
  filters: {
    teachings: [
      'None',
      'Early_Christian',
      'Medieval_Christian',
      'Renaissance',
      'Reformation',
      'Modern_Christian',
    ],
    miracles: [
      'None',
      'Early_Christian',
      'Medieval_Christian',
      'Renaissance',
      'Reformation',
      'Modern_Christian',
    ],
    prayers: [
      'healing',
      'family',
      'finance',
      'spiritual',
      'peace',
      'guidance',
      'protection',
      'hope',
      'grief',
      'love',
      'strength',
      'wisdom',
      'forgiveness',
    ],
    quotes: [
      'none',
      'faith',
      'hope',
      'love',
      'prayer',
      'charity',
      'suffering',
      'forgiveness',
      'humility',
      'peace',
      'joy',
      'wisdom',
      'patience',
      'courage',
      'gratitude',
      'justice',
      'truth',
      'mercy',
      'devotion',
      'unity',
      'passions',
      'mary',
      'saints',
      'sin',
    ],
  },
}
