import glob
R=[
("Yet she knew only three prayers, which her mother had taught her, and she could not read.","Yet she knew only the three prayers her mother had taught her, and she could not read."),
("It began when she was about thirteen, at noon on a summer day, in her father's garden.","It began in her father's garden at noon on a summer day, when she was about thirteen."),
("Every spring, on a Sunday in Lent, the children of the village","On a Sunday in Lent each spring the children of the village"),
("Out in the fields, when she heard the church bell ring, she knelt down where she was.","When she heard the church bell ring out in the fields, she knelt down where she was."),
("and she saw him before her eyes, surrounded by the angels of heaven.","and she saw him before her eyes with the angels of heaven all around him."),
("From then on, more than anything, she wanted","From then on she wanted more than anything"),
("The king she would serve, Charles, had not yet been crowned, and people still called him the Dauphin.","The king she would serve was Charles. He had not yet been crowned, and people still called him the Dauphin."),
("When she left, the captain said to her, “Go,","As she left, the captain told her: “Go,"),
("The duke of Alençon, a prince of the king's own blood, was out at Saint-Florent hunting quail","The duke of Alençon was a prince of the king's own blood. He was out at Saint-Florent hunting quail"),
("After that gift, she said, the King of Heaven would do for him what He had done for the kings before him, and would set him back in his former state.","She said that after that gift the King of Heaven would do for him what He had done for the kings before him. He would set him back in his former state."),
("One of them, a friar who spoke the dialect of the Limousin, asked","A friar who spoke the dialect of the Limousin asked"),
("When it set out, the priests walked ahead of the soldiers behind a banner of their own, singing the Veni Creator, the hymn to the Holy Spirit.","When it set out, the priests walked ahead of the soldiers behind a banner of their own. They sang the Veni Creator, the hymn to the Holy Spirit."),
("On 4 May, while she was up in her room, fighting began outside the walls.","On 4 May fighting began outside the walls while she was up in her room."),
("Her steward, Jean d'Aulon, was down in the ditch","Her steward Jean d'Aulon was down in the ditch"),
("Early the next morning, Sunday 8 May, the English","Early on Sunday 8 May the English"),
("She had four tasks: to drive out the English, to have the king crowned at Reims, to free the duke of Orléans from the English, and to raise the siege of Orléans. They must work well that year, she told him, because she would last a year, and little more.","She had four tasks. She must drive out the English and have the king crowned at Reims. She must free the duke of Orléans from the English and raise the siege of Orléans. She told the king that they must work well that year. She would last a year, and little more."),
("Then messengers came from the king, who had stayed behind at Saint-Denis, and called her back to him.","The king had stayed behind at Saint-Denis, and now his messengers came and called her back to him."),
("Then, with great sorrow, she went along with the king.","Then she went along with the king, with great sorrow."),
("She was very unhappy at the parting, most of all at losing the duke,","She was very unhappy at the parting and most of all at losing the duke,"),
("That day, Monday 23 May 1430, she rode out","On Monday 23 May 1430 she rode out"),
("Her steward, who had served her before she was taken, served her there in prison.","Her steward had served her before she was taken, and he served her there in prison too."),
("The people of Compiègne, every one of them down to the children of seven, were to be put to fire and blood.","All the people of Compiègne were to be put to fire and blood, down to the children of seven."),
("She did it, she said, not out of despair, but hoping to save her body and to go and help the many good people who were in need.","She said she did it not out of despair. She hoped to save her body and to go and help the many good people who were in need."),
("The leap from Beaurevoir, she told her judges, was the thing that had most angered her saints, and she had begged their mercy for it.","She told her judges that the leap from Beaurevoir was the thing that had most angered her saints. She had begged their mercy for it."),
("The English kept her in the castle, in irons, with English soldiers to guard her.","The English kept her in irons in the castle, with English soldiers to guard her."),
("Her judge, Bishop Pierre Cauchon of Beauvais, could have sent her to a church prison, and he would not.","Her judge was Bishop Pierre Cauchon of Beauvais. He could have sent her to a church prison, and he would not."),
("On Saturday 24 February, two days after she had told them of her father's garden, they asked her when she had last eaten.","On Saturday 24 February they began by asking her when she had last eaten."),
("Her Voices, she said, had given her things to tell the king, not them.","She said her Voices had given her things to tell the king, not them."),
("A friar, Isambart de la Pierre, advised","A friar named Isambart de la Pierre advised"),
("The record was read, and she was right, so she told him","The record was read and she was proved right. So she told him"),
("Then, on the morning of Thursday 24 May, they led her out","On the morning of Thursday 24 May they led her out"),
("A famous preacher, Guillaume Érard, took","A famous preacher named Guillaume Érard took"),
("Charles, he cried, who called himself king of France, was a heretic and a schismatic, a man who had broken away from the Church, because he had joined himself to the words and deeds of a worthless woman.","He cried out that the man who called himself king of France was a heretic and a schismatic, a man who had broken away from the Church. Charles had joined himself to the words and deeds of a worthless woman."),
("The preacher turned to the court usher, Jean Massieu, who was there with her.","The preacher turned to the court usher Jean Massieu, who was there with her."),
("Afterward a much longer paper, full of confessions in her name, went into the record in its place.","Afterward a much longer paper went into the record in its place, full of confessions in her name."),
("That afternoon, before the churchmen, she took off the man's clothes and put on a woman's dress,","That afternoon she took off the man's clothes before the churchmen and put on a woman's dress,"),
("On Sunday morning, Trinity Sunday, she said to her guards,","On the morning of Trinity Sunday she said to her guards,"),
("At last, from the needs of her body, she had to go out, and she put on the man's clothes.","At last the needs of her body forced her to go out, and she put on the man's clothes."),
("She also told Brother Martin Ladvenu, a Dominican friar, that","She also told Brother Martin Ladvenu that"),
("Isambart saw her weeping, her face wet with tears and disfigured, and he was full of pity.","Isambart saw her weeping. Her face was wet with tears and disfigured, and he was full of pity."),
("Brother Martin Ladvenu came into her cell, with another friar beside him, to tell her","Brother Martin Ladvenu came into her cell with another friar to tell her"),
("Then she called on God, the great Judge, against the wrongs that had been done to her.","Then she appealed to God the great Judge for the great wrongs done to her."),
("A priest, Master Pierre Maurice, came to see her that morning.","That morning a priest named Pierre Maurice came to see her."),
("so loudly that everyone standing there could hear it, and almost all of them wept.","so loudly that everyone standing there could hear it. Almost all of them wept."),
("Hauviette, now a married woman, told them how she had wept.","Hauviette was a married woman now, and she told them how she had wept."),
("D'Aulon had served her for a whole year, and in all that time, he said, he had seen nothing","D'Aulon had served her for a whole year. In all that time he had seen nothing"),
("On 7 July 1456, in the archbishop's palace at Rouen, the judges declared her trial,","On 7 July 1456 the judges met in the archbishop's palace at Rouen. They declared her trial,"),
("Before that packed and joyful crowd, the Pope declared a saint the farm girl who,","Before that packed and joyful crowd the Pope declared her a saint: the farm girl who,"),
("The chronicler Perceval de Cagny, who served the duke of Alençon, gives her age at Chinon as about eighteen.","Perceval de Cagny was a chronicler who served the duke of Alençon. He gives her age at Chinon as about eighteen."),
("Dunois dated her wound at Orléans to “the 27th of May”, but the day was","Dunois dated her wound at Orléans to “the 27th of May”. The day was"),
("Cagny puts her at Beaulieu about four months, and she put her stay in the tower of Beaurevoir at about four months, so this life gives neither length.","Cagny puts her at Beaulieu for about four months. She put her stay in the tower of Beaurevoir at about four months too, so this life gives neither length."),
("That her brother Pierre was taken with her, and the facts of her mother's later life, come from Quicherat's notes.","Quicherat's notes are the source for the capture of her brother Pierre and for her mother's later life."),
]
files=sorted(glob.glob("part-*.html"))
txt={f:open(f).read() for f in files}
for a,b in R:
    hit=[f for f in files if a in txt[f]]
    if not hit: print("MISSING:",a[:70]); continue
    for f in hit: txt[f]=txt[f].replace(a,b)
for f in files: open(f,"w").write(txt[f])
