const properties = {
  all: {
    filterTitle: 'All Catholic and Orthodox Saints',
  },
  orthodox: {
    filterTitle: 'All Orthodox Saints',
  },
  catholic: {
    filterTitle: 'All Catholic Saints',
  },
  saints: {
    presets: ['20th-century-saints', 'patron-saints'],
    organizeBy: ['category', 'month'],
    title: {
      ascetics: 'Ascetic',
      bishops: 'Bishop',
      confessors: 'Confessor',
      converts: 'Convert',
      fathers_of_the_church: 'Fathers of the Church',
      fools_for_christ: 'Fools for Christ',
      hermits: 'Hermit',
      holy_women: 'Holy Women',
      married: 'Married',
      martyrs: 'Martyr',
      miracle_workers: 'Miracle Working',
      missionaries: 'Missionary',
      monastics: 'Monastic',
      mothers: 'Mother',
      nuns: 'Nun',
      warriors: 'Warrior',
      january: 'January',
      february: 'February',
      april: 'April',
      march: 'March',
      may: 'May',
      june: 'June',
      july: 'July',
      august: 'August',
      september: 'September',
      october: 'October',
      november: 'November',
      december: 'December',
      hope: 'Hope',
      healing: 'Healing',
      family: 'Family',
      finance: 'Finance',
      peace: 'Peace',
      guidance: 'Guidance',
      protection: 'Protection',
      hope: 'Hope',
      grief: 'Grief',
      love: 'Love',
      strength: 'Strength',
      wisdom: 'Wisdom',
      forgiveness: 'Forgiveness',
    },
    filters: {
      category: [
        'All',
        'Ascetics',
        'Bishops',
        'Confessors',
        'Converts',
        'Fathers_of_the_Church',
        'Fools_for_Christ',
        'Hermits',
        'Holy_Women',
        'Married',
        'Martyrs',
        'Miracle_Workers',
        'Missionaries',
        'Monastics',
        'Mothers',
        'Nuns',
        'Warriors',
      ],
      month: [
        'All',
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ],
    },
  },
  books: {
    presets: [
      'theology_and_dogma',
      'spiritual_and_ascetic_writings',
      'church_history_and_biography',
      'prayer_and_devotionals',
    ],
  },
  teachings: {
    filters: [
      'all',
      'apostolic_era',
      'patristic_age',
      'medieval_period',
      'renaissance',
      'modern_era',
    ],
  },
  miracles: {
    filters: [
      'all',
      'apostolic_era',
      'patristic_age',
      'medieval_period',
      'renaissance',
      'modern_era',
    ],
  },
  prayers: {
    filters: [
      'all',
      'healing',
      'family',
      'finance',
      'peace',
      'guidance',
      'protection',
      'hope',
      'grief',
      'love',
      'strength',
      'wisdom',
      'forgiveness',
    ],
  },
  quotes: {
    filters: [
      'all',
      'faith',
      'hope',
      'love',
      'prayer',
      'charity',
      'suffering',
      'forgiveness',
      'humility',
      'peace',
      'joy',
      'wisdom',
      'patience',
      'courage',
      'gratitude',
      'justice',
      'truth',
      'mercy',
      'devotion',
      'unity',
      'passions',
      'mary',
      'saints',
      'sin',
    ],
  },
}

module.exports = { properties }
